// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: auth.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const registerWithDevice = `-- name: RegisterWithDevice :one
WITH u AS (
  INSERT INTO users (email, pwd_phc, e2ee_pub)
  VALUES ($1, $2, $3)
  RETURNING id
),
d AS (
  INSERT INTO devices (user_id, device_id)
  SELECT u.id, $4
  FROM u
  RETURNING device_id
)
SELECT
  (SELECT id FROM u)        AS user_id,
  (SELECT device_id FROM d) AS device_id
`

type RegisterWithDeviceParams struct {
	Email    string
	PwdPhc   string
	E2eePub  []byte
	DeviceID string
}

type RegisterWithDeviceRow struct {
	UserID   uuid.UUID
	DeviceID string
}

func (q *Queries) RegisterWithDevice(ctx context.Context, arg RegisterWithDeviceParams) (RegisterWithDeviceRow, error) {
	row := q.db.QueryRowContext(ctx, registerWithDevice,
		arg.Email,
		arg.PwdPhc,
		arg.E2eePub,
		arg.DeviceID,
	)
	var i RegisterWithDeviceRow
	err := row.Scan(&i.UserID, &i.DeviceID)
	return i, err
}
