// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type File struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Filename  string
	SizeBytes int64
	Path      string
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	PwdPhc    string
	E2eePub   []byte
	CreatedAt time.Time
}
