name: CI (build & test)
on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: '1.25' }
      - run: go test ./...
      - run: |
          mkdir -p dist
          go build -o dist/server ./cmd/server
      - uses: actions/upload-artifact@v4
        with:
          name: server-linux-amd64
          path: dist/server
